stages:
  load_data:
    cmd: python src/load_data.py --config=param.yaml
    deps:
    - src/get_data.py
    - src/load_data.py
    - data_given/winequality_red.csv
    outs:
    - data/raw/winequlity_red.csv


  split_data:
    cmd: python src/split_data.py --config=param.yaml
    deps:
    - src/split_data.py
    - data/raw/winequlity_red.csv
    outs:
    - data/processed/train_winequality.csv
    - data/processed/test_winequality.csv



