stages:
  load_data:
    cmd: python src/load_data.py --config=param.yaml
    deps:
    - src/get_data.py
    - src/load_data.py
    - data_given/winequality_red.csv
    outs:
    - data/raw/winequlity_red.csv



