base:
  project: simple-dvc-project
  random_state: 42
  target_col: TARGET
  test_size: 0.2

data_source:
  s3_source: data_given/winequality_red.csv

load_data:
  raw_dataset_csv:data/raw/winequality_red.csv


  split_data:
    processed_data_dir: data/processed_data
    train_path: data/processed/train_winequality.csv
    test_path: data/processed/test_winequality.csv
    test_size: 0.2

  reports:
    reports_dir: report
    params: report/params.json
    scores: report/scores.json



estimators:
  ElasticNet:
    params:
      alpha: 0.88
      l1_ratio: 0.89

model_dir: saved_models