base:
  project: simple-dvc-project
  random_state: 32
  target_column: quality
  


data_source:
  s3_source: data_given/winequality_red.csv


load_data:
  raw_dataset_csv: data/raw/winequlity_red.csv


split_data:
  train_path: data/processed/train_winequality.csv
  test_path: data/processed/test_winequality.csv
  test_size: 0.2


reports:
  params: report/params.json
  scores: report/scores.json


estimators:
  ElasticNet:
    params:
      alpha: 0.30
      l1_ratio: 0.20

model_dir: saved_models
  

